// AUTO-GENERATED by `powder generate` — do not edit.
// Regenerate after changing powder.schema.json.

import { Client, PowderTable, type TableMeta } from "../../crates/ncode-node/dist/index.js";

/** Row shape of the `users` table. */
export interface Users {
  id: number;
  name: string;
  score: number | null;
  active: boolean;
}

/** AOT-compiled metadata for `users` (SQL precompiled at generation time). */
export const USERS_META: TableMeta = {
  table: "users",
  columns: [
    { name: "id", type: "int", primaryKey: true },
    { name: "name", type: "text" },
    { name: "score", type: "float", nullable: true },
    { name: "active", type: "bool" },
  ],
  sql: {
    selectAll: "SELECT id, name, score, active FROM users",
    insert: "INSERT INTO users (id, name, score, active) VALUES (?, ?, ?, ?)",
    countAll: "SELECT COUNT(*) AS n FROM users",
    deleteAll: "DELETE FROM users",
    ident: {
      id: "id",
      name: "name",
      score: "score",
      active: "active",
    },
  },
};

/** Row shape of the `posts` table. */
export interface Posts {
  id: number;
  user_id: number;
  title: string;
  /** Loaded via `include: { user: true }`. */
  user?: Users | null;
}

/** AOT-compiled metadata for `posts` (SQL precompiled at generation time). */
export const POSTS_META: TableMeta = {
  table: "posts",
  columns: [
    { name: "id", type: "int", primaryKey: true },
    { name: "user_id", type: "int" },
    { name: "title", type: "text" },
  ],
  sql: {
    selectAll: "SELECT id, user_id, title FROM posts",
    insert: "INSERT INTO posts (id, user_id, title) VALUES (?, ?, ?)",
    countAll: "SELECT COUNT(*) AS n FROM posts",
    deleteAll: "DELETE FROM posts",
    ident: {
      id: "id",
      user_id: "user_id",
      title: "title",
    },
  },
  relations: [
    { name: "user", localColumn: "user_id", foreignColumn: "id", target: () => USERS_META },
  ],
};

/** The unified Powder client: one typed handle per table. */
export interface PowderClient {
  users: PowderTable<Users>;
  posts: PowderTable<Posts>;
  /** Run `fn` inside BEGIN IMMEDIATE; commits on return, rolls back on throw. */
  $transaction<T>(fn: (tx: PowderClient) => Promise<T>): Promise<T>;
}

/** Wrap a connected Ncode client with the Powder model layer. */
export function powder(client: Client): PowderClient {
  const api: PowderClient = {
    users: new PowderTable<Users>(client, USERS_META),
    posts: new PowderTable<Posts>(client, POSTS_META),
    $transaction: (fn) => client.transaction(() => fn(api)),
  };
  return api;
}
