# AUTO-GENERATED by `powder generate` — do not edit.
# Regenerate after changing powder.schema.json.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional

from powder import Client
from powder.orm import ColumnMeta, PowderTable, RelationMeta, TableMeta, run_named_query

@dataclass(kw_only=True)
class Users:
    """Row shape of the `users` table."""

    id: int
    name: str
    score: Optional[float] = None
    active: bool
    # Loaded via include={"posts": True}.
    posts: List[Posts] = field(default_factory=list)

USERS_META = TableMeta(
    table="users",
    columns=[
        ColumnMeta(name="id", type="int", nullable=False, primary_key=True),
        ColumnMeta(name="name", type="text", nullable=False, primary_key=False),
        ColumnMeta(name="score", type="float", nullable=True, primary_key=False),
        ColumnMeta(name="active", type="bool", nullable=False, primary_key=False),
    ],
    select_all="SELECT id, name, score, active FROM users",
    insert="INSERT INTO users (id, name, score, active) VALUES (?, ?, ?, ?)",
    count_all="SELECT COUNT(*) AS n FROM users",
    delete_all="DELETE FROM users",
    ident={
        "id": "id",
        "name": "name",
        "score": "score",
        "active": "active",
    },
    relations=(
        RelationMeta(name="posts", kind="hasMany", local_columns=["id"], foreign_columns=["user_id"], target=lambda: POSTS_META),
    ),
)

@dataclass(kw_only=True)
class Posts:
    """Row shape of the `posts` table."""

    id: int
    user_id: int
    title: str
    # Loaded via include={"user": True}.
    user: Optional[Users] = None

POSTS_META = TableMeta(
    table="posts",
    columns=[
        ColumnMeta(name="id", type="int", nullable=False, primary_key=True),
        ColumnMeta(name="user_id", type="int", nullable=False, primary_key=False),
        ColumnMeta(name="title", type="text", nullable=False, primary_key=False),
    ],
    select_all="SELECT id, user_id, title FROM posts",
    insert="INSERT INTO posts (id, user_id, title) VALUES (?, ?, ?)",
    count_all="SELECT COUNT(*) AS n FROM posts",
    delete_all="DELETE FROM posts",
    ident={
        "id": "id",
        "user_id": "user_id",
        "title": "title",
    },
    relations=(
        RelationMeta(name="user", kind="belongsTo", local_columns=["user_id"], foreign_columns=["id"], target=lambda: USERS_META),
    ),
)

_ROW_TYPES = {
    "users": Users,
    "posts": Posts,
}

class PowderQueries:
    """Custom named queries from powder.schema.json (SQL compiled at generation time)."""

    def __init__(self, client: Client):
        self._client = client

    async def topUsers(self, *, active: bool, minScore: float) -> list[Users]:
        """``SELECT id, name, score, active FROM users WHERE active = :active AND score >= :minScore ORDER BY score DESC``"""
        return await run_named_query(self._client, "SELECT id, name, score, active FROM users WHERE active = ? AND score >= ? ORDER BY score DESC", ["active", "minScore"], {"active": active, "minScore": minScore}, meta=USERS_META, row_type=Users)

class PowderClient:
    """The unified Powder client: one typed handle per table."""

    def __init__(self, client: Client):
        self._client = client
        self.users = PowderTable(client, USERS_META, Users, row_types=_ROW_TYPES)
        self.posts = PowderTable(client, POSTS_META, Posts, row_types=_ROW_TYPES)
        #: Custom named queries: ``await db.queries.name(...)``.
        self.queries = PowderQueries(client)

    def transaction(self):
        """``async with db.transaction(): ...`` — commit on exit, rollback on error."""
        return self._client.transaction()

def powder(client: Client) -> PowderClient:
    """Wrap a connected Powder client with the Powder model layer."""
    return PowderClient(client)
