"""Powder ORM — the model layer over the Powder driver (Python mirror).

A :class:`PowderTable` is constructed from AOT-compiled metadata (emitted by
``powder generate`` from ``powder.schema.json``): the SQL skeletons for every
base operation are precompiled strings, and column identifiers are resolved at
generation time. At runtime no query is parsed or re-planned — fragments are
concatenated and parameters bound.

Errors are wrapped in :class:`PowderError`, which carries the failing SQL and
the *caller's* source location (``file:line``) so terminals render a clickable
"warp" link straight to the offending Python line.

Example
-------
>>> from powder import connect
>>> from powder_models import powder          # generated by `powder generate`
>>> db = powder(await connect("sqlite::memory:"))
>>> await db.users.create({"id": 1, "name": "alice", "score": 9.5, "active": True})
>>> top = await db.users.find_many(where={"score": {"gte": 5}}, order_by={"id": "asc"})
"""

from __future__ import annotations

import dataclasses
import traceback
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, Generic, Mapping, Optional, Sequence, Type, TypeVar

if TYPE_CHECKING:  # circular-import-free; Batch is duck-typed at runtime
    from ._reader import Batch

T = TypeVar("T")

_OPS = {
    "eq": "=",
    "ne": "<>",
    "gt": ">",
    "gte": ">=",
    "lt": "<",
    "lte": "<=",
    "like": "LIKE",
    "in": "IN",
}


@dataclass(frozen=True)
class ColumnMeta:
    name: str
    type: str  # "int" | "float" | "text" | "bool"
    nullable: bool = False
    primary_key: bool = False


@dataclass(frozen=True)
class RelationMeta:
    """A relation derived from a foreign key.

    - ``belongsTo``: this table's FK points at ``target`` — one row (or None).
    - ``hasMany``: ``target``'s FK points back — a list of rows.

    Columns are ordered lists so composite (multi-column) keys join correctly:
    row ``r`` matches target row ``t`` iff ``r[local_columns[i]] ==
    t[foreign_columns[i]]`` for every ``i``.
    """

    name: str
    kind: str  # "belongsTo" | "hasMany"
    local_columns: Sequence[str]
    foreign_columns: Sequence[str]
    #: Thunk so mutually-referencing tables can be declared in any order.
    target: Any  # Callable[[], TableMeta]


@dataclass(frozen=True)
class TableMeta:
    """AOT-compiled table metadata (normally emitted by ``powder generate``)."""

    table: str
    columns: Sequence[ColumnMeta]
    select_all: str
    insert: str
    count_all: str
    delete_all: str
    ident: Mapping[str, str] = field(default_factory=dict)
    relations: Sequence[RelationMeta] = ()


class PowderError(RuntimeError):
    """A database error mapped back to the caller's source location."""

    def __init__(self, message: str, sql: str, site: Optional[str] = None):
        text = f"{message}\n  query: {sql}"
        if site:
            text += f"\n  at {site}"
        super().__init__(text)
        self.sql = sql
        self.site = site


def _call_site() -> Optional[str]:
    """First stack frame outside this module — the application call site."""
    for frame in reversed(traceback.extract_stack()[:-1]):
        if frame.filename != __file__:
            return f"{frame.filename}:{frame.lineno}"
    return None


def _coerce(value: Any, column_type: str) -> Any:
    if value is None:
        return None
    if column_type == "bool":
        return bool(value)
    return value


def _materialize_batch(batch: "Batch", meta: TableMeta, row_type: Optional[type]) -> list:
    """Materialize a batch into rows following a table's column meta."""
    cols = [(c, batch.column(c.name)) for c in meta.columns]
    out: list = []
    for r in range(batch.num_rows):
        row = {
            cm.name: _coerce(col.get(r) if col else None, cm.type)
            for cm, col in cols
        }
        out.append(row_type(**row) if row_type else row)
    return out


async def run_named_query(
    client: Any,
    sql: str,
    param_order: Sequence[str],
    args: Mapping[str, Any],
    meta: Optional[TableMeta] = None,
    row_type: Optional[type] = None,
) -> list:
    """Execute an AOT-compiled named query (schema ``queries`` section).

    ``sql`` already uses positional ``?``; ``param_order`` maps each slot to a
    named argument. With ``meta``/``row_type`` rows come back typed; without,
    as plain dicts. Called through the generated ``db.queries`` object.
    """
    site = _call_site()
    params: list[Any] = []
    for p in param_order:
        if p not in args:
            raise PowderError(f"missing parameter `{p}`", sql, site)
        params.append(args[p])
    try:
        batch = await client.query(sql, params)
    except PowderError:
        raise
    except Exception as err:  # noqa: BLE001 — driver errors are opaque
        raise PowderError(str(err), sql, site) from err
    if meta is not None:
        return _materialize_batch(batch, meta, row_type)
    return batch.to_rows()


class PowderTable(Generic[T]):
    """A typed table handle: the unified CRUD surface of Powder ORM."""

    def __init__(
        self,
        client: Any,
        meta: TableMeta,
        row_type: Optional[Type[T]] = None,
        row_types: Optional[Mapping[str, type]] = None,
    ):
        self._client = client
        self.meta = meta
        self._row_type = row_type
        #: table name -> row dataclass, for materializing included relations.
        self._row_types = row_types or {}

    # -- where / tail compilation --------------------------------------

    def _ident(self, column: str, site: Optional[str], qualify: Optional[str] = None) -> str:
        ident = self.meta.ident.get(column)
        if ident is None:
            raise PowderError(f"unknown column `{column}`", self.meta.table, site)
        return f"{qualify}.{ident}" if qualify else ident

    def _compile_where(
        self,
        where: Optional[Mapping[str, Any]],
        site: Optional[str],
        qualify: Optional[str] = None,
    ) -> tuple[str, list[Any]]:
        if not where:
            return "", []
        parts: list[str] = []
        params: list[Any] = []
        for column, cond in where.items():
            ident = self._ident(column, site, qualify)
            if cond is None:
                parts.append(f"{ident} IS NULL")
            elif isinstance(cond, Mapping):
                for op, value in cond.items():
                    sql_op = _OPS.get(op)
                    if sql_op is None:
                        raise PowderError(
                            f"unknown operator `{op}` for column `{column}`",
                            self.meta.table,
                            site,
                        )
                    if op == "in":
                        values = list(value)
                        if not values:
                            parts.append("1 = 0")  # IN () matches nothing
                        else:
                            parts.append(f"{ident} IN ({', '.join('?' * len(values))})")
                            params.extend(values)
                    elif op == "ne" and value is None:
                        parts.append(f"{ident} IS NOT NULL")
                    elif op == "eq" and value is None:
                        parts.append(f"{ident} IS NULL")
                    else:
                        parts.append(f"{ident} {sql_op} ?")
                        params.append(value)
            else:
                parts.append(f"{ident} = ?")
                params.append(cond)
        clause = f" WHERE {' AND '.join(parts)}" if parts else ""
        return clause, params

    def _compile_tail(
        self,
        order_by: Optional[Mapping[str, str]],
        limit: Optional[int],
        offset: Optional[int],
        site: Optional[str],
        qualify: Optional[str] = None,
    ) -> str:
        tail = ""
        if order_by:
            keys = [
                f"{self._ident(col, site, qualify)} {'DESC' if str(direction).lower() == 'desc' else 'ASC'}"
                for col, direction in order_by.items()
            ]
            tail += f" ORDER BY {', '.join(keys)}"
        if limit is not None:
            tail += f" LIMIT {int(limit)}"
        if offset is not None:
            tail += f" OFFSET {int(offset)}"
        return tail

    # -- row materialization --------------------------------------------

    def _rows_of(self, batch: Batch) -> list[T]:
        return _materialize_batch(batch, self.meta, self._row_type)

    def _materialize(self, batch: Batch, meta: TableMeta, row_type: Optional[type]) -> list:
        return _materialize_batch(batch, meta, row_type)

    @staticmethod
    def _get(row: Any, col: str) -> Any:
        return row.get(col) if isinstance(row, dict) else getattr(row, col, None)

    @staticmethod
    def _set(row: Any, name: str, value: Any) -> None:
        if isinstance(row, dict):
            row[name] = value
        else:
            setattr(row, name, value)

    def _tuple_key(self, row: Any, cols: Sequence[str]) -> Optional[tuple]:
        vals = []
        for c in cols:
            v = self._get(row, c)
            if v is None:
                return None
            vals.append(v)
        return tuple(vals)

    def _find_relation(self, name: str, site: Optional[str]) -> RelationMeta:
        rel = next((r for r in self.meta.relations if r.name == name), None)
        if rel is None:
            raise PowderError(
                f"unknown relation `{name}` (no foreign key on {self.meta.table} defines it)",
                self.meta.table,
                site,
            )
        return rel

    def _find_relation_on(self, meta: TableMeta, name: str, site: Optional[str]) -> RelationMeta:
        rel = next((r for r in meta.relations if r.name == name), None)
        if rel is None:
            raise PowderError(
                f"unknown relation `{name}` (no foreign key on {meta.table} defines it)",
                meta.table,
                site,
            )
        return rel

    async def _attach_relations(
        self, rows: list, include: Mapping[str, Any], meta: TableMeta, site: Optional[str]
    ) -> None:
        """Batch-load ``include``d relations and attach them to the rows.

        One ``IN`` query per relation over the distinct key tuples (no N+1);
        ``belongsTo`` attaches one row (or None), ``hasMany`` a list. A dict
        value nests: ``include={"user": {"include": {"posts": True}}}`` loads
        each row's user and then every user's posts, one batched query per
        relation level.
        """
        for name, spec in include.items():
            if not spec:
                continue
            rel = self._find_relation_on(meta, name, site)
            target: TableMeta = rel.target()
            target_type = self._row_types.get(target.table)

            tuples: dict[tuple, tuple] = {}
            for row in rows:
                k = self._tuple_key(row, rel.local_columns)
                if k is not None and k not in tuples:
                    tuples[k] = k

            grouped: dict[tuple, list] = {}
            flat: list = []
            fidents = [target.ident.get(c, c) for c in rel.foreign_columns]
            tuple_list = list(tuples.values())
            single = len(rel.foreign_columns) == 1
            for start in range(0, len(tuple_list), 500):
                chunk = tuple_list[start : start + 500]
                params: list[Any] = []
                if single:
                    clause = f"{fidents[0]} IN ({', '.join('?' * len(chunk))})"
                    params = [t[0] for t in chunk]
                else:
                    cols = ", ".join(fidents)
                    row_ph = f"({', '.join('?' * len(fidents))})"
                    clause = f"({cols}) IN ({', '.join([row_ph] * len(chunk))})"
                    for t in chunk:
                        params.extend(t)
                batch = await self._query(f"{target.select_all} WHERE {clause}", params, site)
                for trow in self._materialize(batch, target, target_type):
                    k = self._tuple_key(trow, rel.foreign_columns)
                    if k is None:
                        continue
                    flat.append(trow)
                    grouped.setdefault(k, []).append(trow)

            # Nested include: recurse over the loaded target rows.
            nested = spec.get("include") if isinstance(spec, Mapping) else None
            if nested and flat:
                await self._attach_relations(flat, nested, target, site)

            for row in rows:
                k = self._tuple_key(row, rel.local_columns)
                matches = grouped.get(k, []) if k is not None else []
                self._set(row, rel.name, matches if rel.kind == "hasMany" else (matches[0] if matches else None))

    async def _find_many_joined(
        self,
        where: Optional[Mapping[str, Any]],
        order_by: Optional[Mapping[str, str]],
        limit: Optional[int],
        offset: Optional[int],
        join: Mapping[str, bool],
        site: Optional[str],
    ) -> list:
        """Single-query path: LEFT JOIN each ``belongsTo`` relation and hydrate
        the nested object from aliased columns."""
        table = self.meta.table
        rels = []
        for name, wanted in join.items():
            if not wanted:
                continue
            rel = self._find_relation(name, site)
            if rel.kind != "belongsTo":
                raise PowderError(
                    f"relation `{name}` is hasMany; use include (a JOIN would multiply rows)",
                    table,
                    site,
                )
            rels.append(rel)

        selects = [f"{table}.{c.name} AS {c.name}" for c in self.meta.columns]
        joins = []
        for rel in rels:
            target: TableMeta = rel.target()
            alias = f"j_{rel.name}"
            for c in target.columns:
                selects.append(f"{alias}.{c.name} AS {rel.name}__{c.name}")
            on = " AND ".join(
                f"{table}.{lc} = {alias}.{fc}"
                for lc, fc in zip(rel.local_columns, rel.foreign_columns)
            )
            joins.append(f"LEFT JOIN {target.table} AS {alias} ON {on}")

        clause, params = self._compile_where(where, site, table)
        sql = (
            f"SELECT {', '.join(selects)} FROM {table} {' '.join(joins)}"
            + clause
            + self._compile_tail(order_by, limit, offset, site, table)
        )
        batch = await self._query(sql, params, site)

        base_cols = [(c, batch.column(c.name)) for c in self.meta.columns]
        rel_cols = [
            (
                rel,
                [(c, batch.column(f"{rel.name}__{c.name}")) for c in rel.target().columns],
                self._row_types.get(rel.target().table),
            )
            for rel in rels
        ]
        out: list = []
        for r in range(batch.num_rows):
            row = {cm.name: _coerce(col.get(r) if col else None, cm.type) for cm, col in base_cols}
            base = self._row_type(**row) if self._row_type else row
            for rel, cols, target_type in rel_cols:
                present = False
                nested = {}
                for cm, col in cols:
                    v = _coerce(col.get(r) if col else None, cm.type)
                    if v is not None:
                        present = True
                    nested[cm.name] = v
                value = (target_type(**nested) if target_type else nested) if present else None
                self._set(base, rel.name, value)
            out.append(base)
        return out

    async def _query(self, sql: str, params: list[Any], site: Optional[str]) -> Batch:
        try:
            return await self._client.query(sql, params)
        except PowderError:
            raise
        except Exception as err:  # noqa: BLE001 — driver errors are opaque
            raise PowderError(str(err), sql, site) from err

    async def _execute(self, sql: str, params: list[Any], site: Optional[str]) -> int:
        try:
            return await self._client.execute(sql, params)
        except PowderError:
            raise
        except Exception as err:  # noqa: BLE001
            raise PowderError(str(err), sql, site) from err

    # -- CRUD -------------------------------------------------------------

    async def find_many(
        self,
        *,
        where: Optional[Mapping[str, Any]] = None,
        order_by: Optional[Mapping[str, str]] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
        include: Optional[Mapping[str, bool]] = None,
        join: Optional[Mapping[str, bool]] = None,
    ) -> list[T]:
        """SELECT rows, materialized as typed row objects.

        ``include={"user": True}`` loads the relation with a second ``IN``
        query (works for belongsTo and hasMany, composite keys included).
        ``join={"user": True}`` hydrates a belongsTo relation in one LEFT JOIN.
        """
        site = _call_site()
        if join:
            rows = await self._find_many_joined(where, order_by, limit, offset, join, site)
        else:
            clause, params = self._compile_where(where, site)
            sql = self.meta.select_all + clause + self._compile_tail(order_by, limit, offset, site)
            rows = self._rows_of(await self._query(sql, params, site))
        if include:
            await self._attach_relations(rows, include, self.meta, site)
        return rows

    async def find_first(
        self,
        *,
        where: Optional[Mapping[str, Any]] = None,
        order_by: Optional[Mapping[str, str]] = None,
    ) -> Optional[T]:
        """First row matching, or ``None``."""
        rows = await self.find_many(where=where, order_by=order_by, limit=1)
        return rows[0] if rows else None

    def _data_dict(self, data: Any) -> dict[str, Any]:
        if dataclasses.is_dataclass(data) and not isinstance(data, type):
            d = dataclasses.asdict(data)
        else:
            d = dict(data)
        # Drop relation fields (present on generated dataclasses) so they are
        # never mistaken for columns on INSERT/UPDATE.
        if self.meta.relations:
            for rel in self.meta.relations:
                d.pop(rel.name, None)
        return d

    async def create(self, data: Any) -> int:
        """INSERT one row (dict or generated dataclass)."""
        site = _call_site()
        values = self._data_dict(data)
        keys = list(values.keys())
        if len(keys) == len(self.meta.columns):
            params = [values.get(c.name) for c in self.meta.columns]
            return await self._execute(self.meta.insert, params, site)
        idents = [self._ident(k, site) for k in keys]
        sql = (
            f"INSERT INTO {self.meta.table} ({', '.join(idents)}) "
            f"VALUES ({', '.join('?' * len(keys))})"
        )
        return await self._execute(sql, [values[k] for k in keys], site)

    async def create_many(self, rows: Sequence[Any], chunk_size: int = 500) -> int:
        """Bulk INSERT with multi-row VALUES, chunked to keep parameter counts sane."""
        if not rows:
            return 0
        site = _call_site()
        dicts = [self._data_dict(r) for r in rows]
        keys = list(dicts[0].keys())
        idents = [self._ident(k, site) for k in keys]
        row_ph = f"({', '.join('?' * len(keys))})"
        affected = 0
        for start in range(0, len(dicts), chunk_size):
            chunk = dicts[start : start + chunk_size]
            sql = (
                f"INSERT INTO {self.meta.table} ({', '.join(idents)}) "
                f"VALUES {', '.join([row_ph] * len(chunk))}"
            )
            params: list[Any] = []
            for row in chunk:
                params.extend(row[k] for k in keys)
            affected += await self._execute(sql, params, site)
        return affected

    async def update(self, *, where: Mapping[str, Any], data: Mapping[str, Any]) -> int:
        """UPDATE matching rows; returns the affected count."""
        site = _call_site()
        rel_names = {r.name for r in self.meta.relations} if self.meta.relations else set()
        sets = [(k, v) for k, v in data.items() if k not in rel_names]
        if not sets:
            return 0
        set_sql = ", ".join(f"{self._ident(k, site)} = ?" for k, _ in sets)
        clause, params = self._compile_where(where, site)
        sql = f"UPDATE {self.meta.table} SET {set_sql}{clause}"
        return await self._execute(sql, [v for _, v in sets] + params, site)

    async def delete(self, where: Mapping[str, Any]) -> int:
        """DELETE matching rows. An empty where is rejected — use :meth:`delete_all`."""
        site = _call_site()
        clause, params = self._compile_where(where, site)
        if not clause:
            raise PowderError(
                "delete() requires a non-empty where clause; use delete_all() to clear the table",
                self.meta.delete_all,
                site,
            )
        return await self._execute(self.meta.delete_all + clause, params, site)

    async def delete_all(self) -> int:
        """DELETE every row (explicit opt-in)."""
        return await self._execute(self.meta.delete_all, [], _call_site())

    async def count(self, where: Optional[Mapping[str, Any]] = None) -> int:
        """COUNT rows matching ``where``."""
        site = _call_site()
        clause, params = self._compile_where(where, site)
        batch = await self._query(self.meta.count_all + clause, params, site)
        col = batch.column("n")
        value = col.get(0) if col else 0
        return int(value or 0)

    # -- beginner-friendly surface ---------------------------------------

    async def find(self, key: Any) -> Optional[T]:
        """Look up one row by primary key: ``await db.users.find(1)``.

        For composite keys (or any ad-hoc lookup) pass a dict:
        ``await db.grades.find({"student": 1, "course": "math"})``.
        """
        site = _call_site()
        if isinstance(key, Mapping):
            return await self.find_first(where=key)
        pk = [c for c in self.meta.columns if c.primary_key]
        if len(pk) != 1:
            raise PowderError(
                f"find(value) needs a single-column primary key on {self.meta.table}; pass a dict instead",
                self.meta.table,
                site,
            )
        return await self.find_first(where={pk[0].name: key})

    async def all(self) -> list[T]:
        """Every row (chain from :meth:`where` for filters)."""
        return await self.find_many()

    def where(self, **conditions: Any) -> "Finder[T]":
        """Start a chainable query::

            top = await db.users.where(active=True).order_by("score", "desc").limit(10).all()
        """
        return Finder(self, where=dict(conditions))

    def order_by(self, column: str, direction: str = "asc") -> "Finder[T]":
        """Start a chainable query from an ordering."""
        return Finder(self, order_by={column: direction})


class Finder(Generic[T]):
    """A chainable, beginner-friendly query. Build it step by step and finish
    with :meth:`all`, :meth:`first`, or :meth:`count`. Each step returns a new
    Finder, so partial queries can be shared and extended independently."""

    def __init__(
        self,
        table: PowderTable[T],
        *,
        where: Optional[dict] = None,
        order_by: Optional[dict] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
        include: Optional[dict] = None,
        join: Optional[dict] = None,
    ):
        self._table = table
        self._where = where or {}
        self._order_by = order_by or {}
        self._limit = limit
        self._offset = offset
        self._include = include or {}
        self._join = join or {}

    def _extend(self, **patch: Any) -> "Finder[T]":
        state = {
            "where": dict(self._where),
            "order_by": dict(self._order_by),
            "limit": self._limit,
            "offset": self._offset,
            "include": dict(self._include),
            "join": dict(self._join),
        }
        state.update(patch)
        return Finder(self._table, **state)

    def where(self, **conditions: Any) -> "Finder[T]":
        """Add filters; repeated calls merge (same column overrides)."""
        return self._extend(where={**self._where, **conditions})

    def order_by(self, column: str, direction: str = "asc") -> "Finder[T]":
        return self._extend(order_by={**self._order_by, column: direction})

    def limit(self, n: int) -> "Finder[T]":
        return self._extend(limit=n)

    def offset(self, n: int) -> "Finder[T]":
        return self._extend(offset=n)

    def include(self, **relations: Any) -> "Finder[T]":
        """Load relations alongside the rows (values: True or nested dicts)."""
        return self._extend(include={**self._include, **relations})

    def join(self, **relations: bool) -> "Finder[T]":
        """Hydrate belongsTo relations with a single LEFT JOIN query."""
        return self._extend(join={**self._join, **relations})

    async def all(self) -> list[T]:
        """Run the query and return every matching row."""
        return await self._table.find_many(
            where=self._where or None,
            order_by=self._order_by or None,
            limit=self._limit,
            offset=self._offset,
            include=self._include or None,
            join=self._join or None,
        )

    async def first(self) -> Optional[T]:
        """Run the query and return the first row, or ``None``."""
        rows = await self._extend(limit=1).all()
        return rows[0] if rows else None

    async def count(self) -> int:
        """Count matching rows (ignores limit/offset/ordering)."""
        return await self._table.count(self._where or None)
