// AUTO-GENERATED by `powder generate` — do not edit.
// Regenerate after changing powder.schema.json.

import { Client, PowderTable, extendPowder, type ExtendedClient, type PowderExtensions, type TableMeta } from "@powder/node";

/** Row shape of the `customers` table. */
export interface Customers {
  id: number;
  name: string;
  email: string;
  tier: string;
  active: boolean;
  /** Loaded via `include: { orders: true }`. */
  orders?: Orders[];
}

/** Relations loadable on `customers` — powers `include`/`join` autocompletion. */
export type CustomersInclude = {
  orders?: boolean | { include?: OrdersInclude };
};

/** AOT-compiled metadata for `customers` (SQL precompiled at generation time). */
export const CUSTOMERS_META: TableMeta = {
  table: "customers",
  columns: [
    { name: "id", type: "int", primaryKey: true },
    { name: "name", type: "text" },
    { name: "email", type: "text" },
    { name: "tier", type: "text" },
    { name: "active", type: "bool" },
  ],
  sql: {
    selectAll: "SELECT id, name, email, tier, active FROM customers",
    insert: "INSERT INTO customers (id, name, email, tier, active) VALUES (?, ?, ?, ?, ?)",
    countAll: "SELECT COUNT(*) AS n FROM customers",
    deleteAll: "DELETE FROM customers",
    ident: {
      id: "id",
      name: "name",
      email: "email",
      tier: "tier",
      active: "active",
    },
  },
  relations: [
    { name: "orders", kind: "hasMany", localColumns: ["id"], foreignColumns: ["customer_id"], target: () => ORDERS_META },
  ],
};

/** Row shape of the `products` table. */
export interface Products {
  id: number;
  name: string;
  price: number;
  stock: number;
  /** Loaded via `include: { order_items: true }`. */
  order_items?: OrderItems[];
}

/** Relations loadable on `products` — powers `include`/`join` autocompletion. */
export type ProductsInclude = {
  order_items?: boolean | { include?: OrderItemsInclude };
};

/** AOT-compiled metadata for `products` (SQL precompiled at generation time). */
export const PRODUCTS_META: TableMeta = {
  table: "products",
  columns: [
    { name: "id", type: "int", primaryKey: true },
    { name: "name", type: "text" },
    { name: "price", type: "float" },
    { name: "stock", type: "int" },
  ],
  sql: {
    selectAll: "SELECT id, name, price, stock FROM products",
    insert: "INSERT INTO products (id, name, price, stock) VALUES (?, ?, ?, ?)",
    countAll: "SELECT COUNT(*) AS n FROM products",
    deleteAll: "DELETE FROM products",
    ident: {
      id: "id",
      name: "name",
      price: "price",
      stock: "stock",
    },
  },
  relations: [
    { name: "order_items", kind: "hasMany", localColumns: ["id"], foreignColumns: ["product_id"], target: () => ORDER_ITEMS_META },
  ],
};

/** Row shape of the `orders` table. */
export interface Orders {
  id: number;
  customer_id: number;
  status: string;
  amount: number;
  note: string | null;
  /** Loaded via `include: { customer: true }`. */
  customer?: Customers | null;
  /** Loaded via `include: { order_items: true }`. */
  order_items?: OrderItems[];
}

/** Relations loadable on `orders` — powers `include`/`join` autocompletion. */
export type OrdersInclude = {
  customer?: boolean | { include?: CustomersInclude };
  order_items?: boolean | { include?: OrderItemsInclude };
};

/** AOT-compiled metadata for `orders` (SQL precompiled at generation time). */
export const ORDERS_META: TableMeta = {
  table: "orders",
  columns: [
    { name: "id", type: "int", primaryKey: true },
    { name: "customer_id", type: "int" },
    { name: "status", type: "text" },
    { name: "amount", type: "float" },
    { name: "note", type: "text", nullable: true },
  ],
  sql: {
    selectAll: "SELECT id, customer_id, status, amount, note FROM orders",
    insert: "INSERT INTO orders (id, customer_id, status, amount, note) VALUES (?, ?, ?, ?, ?)",
    countAll: "SELECT COUNT(*) AS n FROM orders",
    deleteAll: "DELETE FROM orders",
    ident: {
      id: "id",
      customer_id: "customer_id",
      status: "status",
      amount: "amount",
      note: "note",
    },
  },
  relations: [
    { name: "customer", kind: "belongsTo", localColumns: ["customer_id"], foreignColumns: ["id"], target: () => CUSTOMERS_META },
    { name: "order_items", kind: "hasMany", localColumns: ["id"], foreignColumns: ["order_id"], target: () => ORDER_ITEMS_META },
  ],
};

/** Row shape of the `order_items` table. */
export interface OrderItems {
  id: number;
  order_id: number;
  product_id: number;
  qty: number;
  unit_price: number;
  /** Loaded via `include: { order: true }`. */
  order?: Orders | null;
  /** Loaded via `include: { product: true }`. */
  product?: Products | null;
}

/** Relations loadable on `order_items` — powers `include`/`join` autocompletion. */
export type OrderItemsInclude = {
  order?: boolean | { include?: OrdersInclude };
  product?: boolean | { include?: ProductsInclude };
};

/** AOT-compiled metadata for `order_items` (SQL precompiled at generation time). */
export const ORDER_ITEMS_META: TableMeta = {
  table: "order_items",
  columns: [
    { name: "id", type: "int", primaryKey: true },
    { name: "order_id", type: "int" },
    { name: "product_id", type: "int" },
    { name: "qty", type: "int" },
    { name: "unit_price", type: "float" },
  ],
  sql: {
    selectAll: "SELECT id, order_id, product_id, qty, unit_price FROM order_items",
    insert: "INSERT INTO order_items (id, order_id, product_id, qty, unit_price) VALUES (?, ?, ?, ?, ?)",
    countAll: "SELECT COUNT(*) AS n FROM order_items",
    deleteAll: "DELETE FROM order_items",
    ident: {
      id: "id",
      order_id: "order_id",
      product_id: "product_id",
      qty: "qty",
      unit_price: "unit_price",
    },
  },
  relations: [
    { name: "order", kind: "belongsTo", localColumns: ["order_id"], foreignColumns: ["id"], target: () => ORDERS_META },
    { name: "product", kind: "belongsTo", localColumns: ["product_id"], foreignColumns: ["id"], target: () => PRODUCTS_META },
  ],
};

/** The unified Powder client: one typed handle per table. */
export interface PowderClient {
  customers: PowderTable<Customers, CustomersInclude>;
  products: PowderTable<Products, ProductsInclude>;
  orders: PowderTable<Orders, OrdersInclude>;
  order_items: PowderTable<OrderItems, OrderItemsInclude>;
  /** Graft your own table methods: `db.$extend({ posts: { publishAll() {...} } })`. */
  $extend<E extends PowderExtensions>(ext: E): ExtendedClient<PowderClient, E>;
  /** Run `fn` inside BEGIN IMMEDIATE; commits on return, rolls back on throw. */
  $transaction<T>(fn: (tx: PowderClient) => Promise<T>): Promise<T>;
}

/** Wrap a connected Powder client with the Powder model layer. */
export function powder(client: Client): PowderClient {
  const api: PowderClient = {
    customers: new PowderTable<Customers, CustomersInclude>(client, CUSTOMERS_META),
    products: new PowderTable<Products, ProductsInclude>(client, PRODUCTS_META),
    orders: new PowderTable<Orders, OrdersInclude>(client, ORDERS_META),
    order_items: new PowderTable<OrderItems, OrderItemsInclude>(client, ORDER_ITEMS_META),
    $extend: (ext) => extendPowder(api, ext),
    $transaction: (fn) => client.transaction(() => fn(api)),
  };
  return api;
}
