# AUTO-GENERATED by `powder generate` — do not edit.
# Regenerate after changing powder.schema.json.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional

from powder import Client
from powder.orm import ColumnMeta, PowderTable, RelationMeta, TableMeta, run_named_query

@dataclass(kw_only=True)
class Customers:
    """Row shape of the `customers` table."""

    id: int
    name: str
    email: str
    tier: str
    active: bool
    # Loaded via include={"orders": True}.
    orders: List[Orders] = field(default_factory=list)

CUSTOMERS_META = TableMeta(
    table="customers",
    columns=[
        ColumnMeta(name="id", type="int", nullable=False, primary_key=True),
        ColumnMeta(name="name", type="text", nullable=False, primary_key=False),
        ColumnMeta(name="email", type="text", nullable=False, primary_key=False),
        ColumnMeta(name="tier", type="text", nullable=False, primary_key=False),
        ColumnMeta(name="active", type="bool", nullable=False, primary_key=False),
    ],
    select_all="SELECT id, name, email, tier, active FROM customers",
    insert="INSERT INTO customers (id, name, email, tier, active) VALUES (?, ?, ?, ?, ?)",
    count_all="SELECT COUNT(*) AS n FROM customers",
    delete_all="DELETE FROM customers",
    ident={
        "id": "id",
        "name": "name",
        "email": "email",
        "tier": "tier",
        "active": "active",
    },
    relations=(
        RelationMeta(name="orders", kind="hasMany", local_columns=["id"], foreign_columns=["customer_id"], target=lambda: ORDERS_META),
    ),
)

@dataclass(kw_only=True)
class Products:
    """Row shape of the `products` table."""

    id: int
    name: str
    price: float
    stock: int
    # Loaded via include={"order_items": True}.
    order_items: List[OrderItems] = field(default_factory=list)

PRODUCTS_META = TableMeta(
    table="products",
    columns=[
        ColumnMeta(name="id", type="int", nullable=False, primary_key=True),
        ColumnMeta(name="name", type="text", nullable=False, primary_key=False),
        ColumnMeta(name="price", type="float", nullable=False, primary_key=False),
        ColumnMeta(name="stock", type="int", nullable=False, primary_key=False),
    ],
    select_all="SELECT id, name, price, stock FROM products",
    insert="INSERT INTO products (id, name, price, stock) VALUES (?, ?, ?, ?)",
    count_all="SELECT COUNT(*) AS n FROM products",
    delete_all="DELETE FROM products",
    ident={
        "id": "id",
        "name": "name",
        "price": "price",
        "stock": "stock",
    },
    relations=(
        RelationMeta(name="order_items", kind="hasMany", local_columns=["id"], foreign_columns=["product_id"], target=lambda: ORDER_ITEMS_META),
    ),
)

@dataclass(kw_only=True)
class Orders:
    """Row shape of the `orders` table."""

    id: int
    customer_id: int
    status: str
    amount: float
    note: Optional[str] = None
    # Loaded via include={"customer": True}.
    customer: Optional[Customers] = None
    # Loaded via include={"order_items": True}.
    order_items: List[OrderItems] = field(default_factory=list)

ORDERS_META = TableMeta(
    table="orders",
    columns=[
        ColumnMeta(name="id", type="int", nullable=False, primary_key=True),
        ColumnMeta(name="customer_id", type="int", nullable=False, primary_key=False),
        ColumnMeta(name="status", type="text", nullable=False, primary_key=False),
        ColumnMeta(name="amount", type="float", nullable=False, primary_key=False),
        ColumnMeta(name="note", type="text", nullable=True, primary_key=False),
    ],
    select_all="SELECT id, customer_id, status, amount, note FROM orders",
    insert="INSERT INTO orders (id, customer_id, status, amount, note) VALUES (?, ?, ?, ?, ?)",
    count_all="SELECT COUNT(*) AS n FROM orders",
    delete_all="DELETE FROM orders",
    ident={
        "id": "id",
        "customer_id": "customer_id",
        "status": "status",
        "amount": "amount",
        "note": "note",
    },
    relations=(
        RelationMeta(name="customer", kind="belongsTo", local_columns=["customer_id"], foreign_columns=["id"], target=lambda: CUSTOMERS_META),
        RelationMeta(name="order_items", kind="hasMany", local_columns=["id"], foreign_columns=["order_id"], target=lambda: ORDER_ITEMS_META),
    ),
)

@dataclass(kw_only=True)
class OrderItems:
    """Row shape of the `order_items` table."""

    id: int
    order_id: int
    product_id: int
    qty: int
    unit_price: float
    # Loaded via include={"order": True}.
    order: Optional[Orders] = None
    # Loaded via include={"product": True}.
    product: Optional[Products] = None

ORDER_ITEMS_META = TableMeta(
    table="order_items",
    columns=[
        ColumnMeta(name="id", type="int", nullable=False, primary_key=True),
        ColumnMeta(name="order_id", type="int", nullable=False, primary_key=False),
        ColumnMeta(name="product_id", type="int", nullable=False, primary_key=False),
        ColumnMeta(name="qty", type="int", nullable=False, primary_key=False),
        ColumnMeta(name="unit_price", type="float", nullable=False, primary_key=False),
    ],
    select_all="SELECT id, order_id, product_id, qty, unit_price FROM order_items",
    insert="INSERT INTO order_items (id, order_id, product_id, qty, unit_price) VALUES (?, ?, ?, ?, ?)",
    count_all="SELECT COUNT(*) AS n FROM order_items",
    delete_all="DELETE FROM order_items",
    ident={
        "id": "id",
        "order_id": "order_id",
        "product_id": "product_id",
        "qty": "qty",
        "unit_price": "unit_price",
    },
    relations=(
        RelationMeta(name="order", kind="belongsTo", local_columns=["order_id"], foreign_columns=["id"], target=lambda: ORDERS_META),
        RelationMeta(name="product", kind="belongsTo", local_columns=["product_id"], foreign_columns=["id"], target=lambda: PRODUCTS_META),
    ),
)

_ROW_TYPES = {
    "customers": Customers,
    "products": Products,
    "orders": Orders,
    "order_items": OrderItems,
}

class PowderClient:
    """The unified Powder client: one typed handle per table."""

    def __init__(self, client: Client):
        self._client = client
        self.customers = PowderTable(client, CUSTOMERS_META, Customers, row_types=_ROW_TYPES)
        self.products = PowderTable(client, PRODUCTS_META, Products, row_types=_ROW_TYPES)
        self.orders = PowderTable(client, ORDERS_META, Orders, row_types=_ROW_TYPES)
        self.order_items = PowderTable(client, ORDER_ITEMS_META, OrderItems, row_types=_ROW_TYPES)

    def transaction(self):
        """``async with db.transaction(): ...`` — commit on exit, rollback on error."""
        return self._client.transaction()

def powder(client: Client) -> PowderClient:
    """Wrap a connected Powder client with the Powder model layer."""
    return PowderClient(client)
