/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Open a connection. Returns a `Promise<Client>`. */
export declare function connect(url: string): Promise<Client>
/** An async database client. Returned by [`connect`]. */
export declare class Client {
  /** Run a non-row statement (INSERT/UPDATE/DDL). Resolves to rows affected. */
  execute(sql: string, params?: Array<ParamValue> | undefined | null): Promise<number>
  /**
   * Run a query. Resolves to a `Buffer` holding the PCB columnar payload,
   * which `decodeBatch()` in the TS wrapper turns into zero-copy typed
   * arrays. The bytes are shared with the core's query cache and handed to
   * V8 as an external buffer — no copy on the way out.
   */
  query(sql: string, params?: Array<ParamValue> | undefined | null): Promise<NcbBuffer>
  /**
   * Synchronous query-cache probe: returns the cached PCB buffer for an
   * identical prior query on an unchanged `:memory:` database, or `null`.
   * A hit skips the async bridge, the thread hop, the scan, and the encode
   * entirely — this is the microsecond path for repeated reads.
   */
  queryCached(sql: string, params?: Array<ParamValue> | undefined | null): NcbBuffer | null
}
