"""Powder ORM — the model layer over the Ncode driver (Python mirror).

A :class:`PowderTable` is constructed from AOT-compiled metadata (emitted by
``powder generate`` from ``powder.schema.json``): the SQL skeletons for every
base operation are precompiled strings, and column identifiers are resolved at
generation time. At runtime no query is parsed or re-planned — fragments are
concatenated and parameters bound.

Errors are wrapped in :class:`PowderError`, which carries the failing SQL and
the *caller's* source location (``file:line``) so terminals render a clickable
"warp" link straight to the offending Python line.

Example
-------
>>> from ncode import connect
>>> from powder_models import powder          # generated by `powder generate`
>>> db = powder(await connect("sqlite::memory:"))
>>> await db.users.create({"id": 1, "name": "alice", "score": 9.5, "active": True})
>>> top = await db.users.find_many(where={"score": {"gte": 5}}, order_by={"id": "asc"})
"""

from __future__ import annotations

import dataclasses
import traceback
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, Generic, Mapping, Optional, Sequence, Type, TypeVar

if TYPE_CHECKING:  # circular-import-free; Batch is duck-typed at runtime
    from ._reader import Batch

T = TypeVar("T")

_OPS = {
    "eq": "=",
    "ne": "<>",
    "gt": ">",
    "gte": ">=",
    "lt": "<",
    "lte": "<=",
    "like": "LIKE",
    "in": "IN",
}


@dataclass(frozen=True)
class ColumnMeta:
    name: str
    type: str  # "int" | "float" | "text" | "bool"
    nullable: bool = False
    primary_key: bool = False


@dataclass(frozen=True)
class RelationMeta:
    """A relation derived from a foreign key (``posts.user_id -> users.id``)."""

    name: str
    local_column: str
    foreign_column: str
    #: Thunk so mutually-referencing tables can be declared in any order.
    target: Any  # Callable[[], TableMeta]


@dataclass(frozen=True)
class TableMeta:
    """AOT-compiled table metadata (normally emitted by ``powder generate``)."""

    table: str
    columns: Sequence[ColumnMeta]
    select_all: str
    insert: str
    count_all: str
    delete_all: str
    ident: Mapping[str, str] = field(default_factory=dict)
    relations: Sequence[RelationMeta] = ()


class PowderError(RuntimeError):
    """A database error mapped back to the caller's source location."""

    def __init__(self, message: str, sql: str, site: Optional[str] = None):
        text = f"{message}\n  query: {sql}"
        if site:
            text += f"\n  at {site}"
        super().__init__(text)
        self.sql = sql
        self.site = site


def _call_site() -> Optional[str]:
    """First stack frame outside this module — the application call site."""
    for frame in reversed(traceback.extract_stack()[:-1]):
        if frame.filename != __file__:
            return f"{frame.filename}:{frame.lineno}"
    return None


def _coerce(value: Any, column_type: str) -> Any:
    if value is None:
        return None
    if column_type == "bool":
        return bool(value)
    return value


class PowderTable(Generic[T]):
    """A typed table handle: the unified CRUD surface of Powder ORM."""

    def __init__(
        self,
        client: Any,
        meta: TableMeta,
        row_type: Optional[Type[T]] = None,
        row_types: Optional[Mapping[str, type]] = None,
    ):
        self._client = client
        self.meta = meta
        self._row_type = row_type
        #: table name -> row dataclass, for materializing included relations.
        self._row_types = row_types or {}

    # -- where / tail compilation --------------------------------------

    def _ident(self, column: str, site: Optional[str]) -> str:
        ident = self.meta.ident.get(column)
        if ident is None:
            raise PowderError(f"unknown column `{column}`", self.meta.table, site)
        return ident

    def _compile_where(
        self, where: Optional[Mapping[str, Any]], site: Optional[str]
    ) -> tuple[str, list[Any]]:
        if not where:
            return "", []
        parts: list[str] = []
        params: list[Any] = []
        for column, cond in where.items():
            ident = self._ident(column, site)
            if cond is None:
                parts.append(f"{ident} IS NULL")
            elif isinstance(cond, Mapping):
                for op, value in cond.items():
                    sql_op = _OPS.get(op)
                    if sql_op is None:
                        raise PowderError(
                            f"unknown operator `{op}` for column `{column}`",
                            self.meta.table,
                            site,
                        )
                    if op == "in":
                        values = list(value)
                        if not values:
                            parts.append("1 = 0")  # IN () matches nothing
                        else:
                            parts.append(f"{ident} IN ({', '.join('?' * len(values))})")
                            params.extend(values)
                    elif op == "ne" and value is None:
                        parts.append(f"{ident} IS NOT NULL")
                    elif op == "eq" and value is None:
                        parts.append(f"{ident} IS NULL")
                    else:
                        parts.append(f"{ident} {sql_op} ?")
                        params.append(value)
            else:
                parts.append(f"{ident} = ?")
                params.append(cond)
        clause = f" WHERE {' AND '.join(parts)}" if parts else ""
        return clause, params

    def _compile_tail(
        self,
        order_by: Optional[Mapping[str, str]],
        limit: Optional[int],
        offset: Optional[int],
        site: Optional[str],
    ) -> str:
        tail = ""
        if order_by:
            keys = [
                f"{self._ident(col, site)} {'DESC' if str(direction).lower() == 'desc' else 'ASC'}"
                for col, direction in order_by.items()
            ]
            tail += f" ORDER BY {', '.join(keys)}"
        if limit is not None:
            tail += f" LIMIT {int(limit)}"
        if offset is not None:
            tail += f" OFFSET {int(offset)}"
        return tail

    # -- row materialization --------------------------------------------

    def _rows_of(self, batch: Batch) -> list[T]:
        return self._materialize(batch, self.meta, self._row_type)

    def _materialize(self, batch: Batch, meta: TableMeta, row_type: Optional[type]) -> list:
        cols = [(c, batch.column(c.name)) for c in meta.columns]
        out: list = []
        for r in range(batch.num_rows):
            row = {
                cm.name: _coerce(col.get(r) if col else None, cm.type)
                for cm, col in cols
            }
            out.append(row_type(**row) if row_type else row)
        return out

    async def _attach_relations(
        self, rows: list, include: Mapping[str, bool], site: Optional[str]
    ) -> None:
        """Batch-load ``include``d relations and attach them to the rows."""
        for name, wanted in include.items():
            if not wanted:
                continue
            rel = next((r for r in self.meta.relations if r.name == name), None)
            if rel is None:
                raise PowderError(
                    f"unknown relation `{name}` (no foreign key on {self.meta.table} defines it)",
                    self.meta.table,
                    site,
                )
            target: TableMeta = rel.target()
            target_type = self._row_types.get(target.table)

            def local(row: Any) -> Any:
                if isinstance(row, dict):
                    return row.get(rel.local_column)
                return getattr(row, rel.local_column, None)

            keys = list({local(row) for row in rows if local(row) is not None})
            by_key: dict[Any, Any] = {}
            fident = target.ident.get(rel.foreign_column, rel.foreign_column)
            for start in range(0, len(keys), 500):
                chunk = keys[start : start + 500]
                sql = (
                    f"{target.select_all} WHERE {fident} "
                    f"IN ({', '.join('?' * len(chunk))})"
                )
                batch = await self._query(sql, chunk, site)
                for trow in self._materialize(batch, target, target_type):
                    key = (
                        trow.get(rel.foreign_column)
                        if isinstance(trow, dict)
                        else getattr(trow, rel.foreign_column)
                    )
                    by_key[key] = trow
            for row in rows:
                value = by_key.get(local(row))
                if isinstance(row, dict):
                    row[rel.name] = value
                else:
                    setattr(row, rel.name, value)

    async def _query(self, sql: str, params: list[Any], site: Optional[str]) -> Batch:
        try:
            return await self._client.query(sql, params)
        except PowderError:
            raise
        except Exception as err:  # noqa: BLE001 — driver errors are opaque
            raise PowderError(str(err), sql, site) from err

    async def _execute(self, sql: str, params: list[Any], site: Optional[str]) -> int:
        try:
            return await self._client.execute(sql, params)
        except PowderError:
            raise
        except Exception as err:  # noqa: BLE001
            raise PowderError(str(err), sql, site) from err

    # -- CRUD -------------------------------------------------------------

    async def find_many(
        self,
        *,
        where: Optional[Mapping[str, Any]] = None,
        order_by: Optional[Mapping[str, str]] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
        include: Optional[Mapping[str, bool]] = None,
    ) -> list[T]:
        """SELECT rows, materialized as typed row objects.

        ``include={"user": True}`` batch-loads the relation derived from the
        table's foreign key and attaches it to each row.
        """
        site = _call_site()
        clause, params = self._compile_where(where, site)
        sql = self.meta.select_all + clause + self._compile_tail(order_by, limit, offset, site)
        rows = self._rows_of(await self._query(sql, params, site))
        if include:
            await self._attach_relations(rows, include, site)
        return rows

    async def find_first(
        self,
        *,
        where: Optional[Mapping[str, Any]] = None,
        order_by: Optional[Mapping[str, str]] = None,
    ) -> Optional[T]:
        """First row matching, or ``None``."""
        rows = await self.find_many(where=where, order_by=order_by, limit=1)
        return rows[0] if rows else None

    def _data_dict(self, data: Any) -> dict[str, Any]:
        if dataclasses.is_dataclass(data) and not isinstance(data, type):
            return dataclasses.asdict(data)
        return dict(data)

    async def create(self, data: Any) -> int:
        """INSERT one row (dict or generated dataclass)."""
        site = _call_site()
        values = self._data_dict(data)
        keys = list(values.keys())
        if len(keys) == len(self.meta.columns):
            params = [values.get(c.name) for c in self.meta.columns]
            return await self._execute(self.meta.insert, params, site)
        idents = [self._ident(k, site) for k in keys]
        sql = (
            f"INSERT INTO {self.meta.table} ({', '.join(idents)}) "
            f"VALUES ({', '.join('?' * len(keys))})"
        )
        return await self._execute(sql, [values[k] for k in keys], site)

    async def create_many(self, rows: Sequence[Any], chunk_size: int = 500) -> int:
        """Bulk INSERT with multi-row VALUES, chunked to keep parameter counts sane."""
        if not rows:
            return 0
        site = _call_site()
        dicts = [self._data_dict(r) for r in rows]
        keys = list(dicts[0].keys())
        idents = [self._ident(k, site) for k in keys]
        row_ph = f"({', '.join('?' * len(keys))})"
        affected = 0
        for start in range(0, len(dicts), chunk_size):
            chunk = dicts[start : start + chunk_size]
            sql = (
                f"INSERT INTO {self.meta.table} ({', '.join(idents)}) "
                f"VALUES {', '.join([row_ph] * len(chunk))}"
            )
            params: list[Any] = []
            for row in chunk:
                params.extend(row[k] for k in keys)
            affected += await self._execute(sql, params, site)
        return affected

    async def update(self, *, where: Mapping[str, Any], data: Mapping[str, Any]) -> int:
        """UPDATE matching rows; returns the affected count."""
        site = _call_site()
        sets = [(k, v) for k, v in data.items()]
        if not sets:
            return 0
        set_sql = ", ".join(f"{self._ident(k, site)} = ?" for k, _ in sets)
        clause, params = self._compile_where(where, site)
        sql = f"UPDATE {self.meta.table} SET {set_sql}{clause}"
        return await self._execute(sql, [v for _, v in sets] + params, site)

    async def delete(self, where: Mapping[str, Any]) -> int:
        """DELETE matching rows. An empty where is rejected — use :meth:`delete_all`."""
        site = _call_site()
        clause, params = self._compile_where(where, site)
        if not clause:
            raise PowderError(
                "delete() requires a non-empty where clause; use delete_all() to clear the table",
                self.meta.delete_all,
                site,
            )
        return await self._execute(self.meta.delete_all + clause, params, site)

    async def delete_all(self) -> int:
        """DELETE every row (explicit opt-in)."""
        return await self._execute(self.meta.delete_all, [], _call_site())

    async def count(self, where: Optional[Mapping[str, Any]] = None) -> int:
        """COUNT rows matching ``where``."""
        site = _call_site()
        clause, params = self._compile_where(where, site)
        batch = await self._query(self.meta.count_all + clause, params, site)
        col = batch.column("n")
        value = col.get(0) if col else 0
        return int(value or 0)
