//! AOT code generation: `powder.schema.json` -> typed model modules.
//!
//! This is the "AOT query compilation" step of the plan: the SQL skeletons for
//! every base CRUD operation and every quoted column identifier are rendered
//! here, at build time. The generated module hands them to the language's
//! Powder runtime, which only binds parameters at run time — no query text is
//! parsed or assembled from scratch per call.

use crate::schema::{Column, Schema, Table};

/// One relation derived from a foreign key: `posts.user_id -> users.id`
/// becomes a `user` relation on `posts`.
struct Relation<'a> {
    name: String,
    local_column: &'a str,
    foreign_column: &'a str,
    target_table: &'a str,
}

fn relations_of<'a>(table: &'a Table) -> Vec<Relation<'a>> {
    let mut used: Vec<String> = Vec::new();
    let mut out = Vec::new();
    for col in &table.columns {
        let Some(r) = &col.def.references else { continue };
        let stem = col.name.strip_suffix("_id").unwrap_or("");
        let mut name = if !stem.is_empty()
            && !table.columns.iter().any(|c| c.name == stem)
            && !used.iter().any(|u| u == stem)
        {
            stem.to_string()
        } else {
            format!("{}_ref", col.name)
        };
        while used.contains(&name) || table.columns.iter().any(|c| c.name == name) {
            name.push('_');
        }
        used.push(name.clone());
        out.push(Relation {
            name,
            local_column: &col.name,
            foreign_column: &r.column,
            target_table: &r.table,
        });
    }
    out
}

fn column_default_py(col: &Column) -> &'static str {
    let _ = col;
    " = None"
}

fn pascal(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut upper = true;
    for c in name.chars() {
        if c == '_' {
            upper = true;
        } else if upper {
            out.extend(c.to_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    out
}

fn shout(name: &str) -> String {
    name.to_ascii_uppercase()
}

fn column_list(table: &Table) -> String {
    table
        .columns
        .iter()
        .map(|c| c.name.as_str())
        .collect::<Vec<_>>()
        .join(", ")
}

fn insert_sql(table: &Table) -> String {
    format!(
        "INSERT INTO {} ({}) VALUES ({})",
        table.name,
        column_list(table),
        vec!["?"; table.columns.len()].join(", ")
    )
}

/// Generate the TypeScript model module.
pub fn typescript(schema: &Schema, import_from: &str) -> String {
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by `powder generate` — do not edit.\n");
    out.push_str("// Regenerate after changing powder.schema.json.\n\n");
    out.push_str(&format!(
        "import {{ Client, PowderTable, type TableMeta }} from \"{import_from}\";\n\n"
    ));

    for table in &schema.tables {
        let ty = pascal(&table.name);
        let relations = relations_of(table);
        out.push_str(&format!("/** Row shape of the `{}` table. */\n", table.name));
        out.push_str(&format!("export interface {ty} {{\n"));
        for col in &table.columns {
            let base = col.def.column_type.ts_type();
            let ts = if col.def.nullable {
                format!("{base} | null")
            } else {
                base.to_string()
            };
            out.push_str(&format!("  {}: {};\n", col.name, ts));
        }
        for rel in &relations {
            out.push_str(&format!(
                "  /** Loaded via `include: {{ {}: true }}`. */\n  {}?: {} | null;\n",
                rel.name,
                rel.name,
                pascal(rel.target_table)
            ));
        }
        out.push_str("}\n\n");

        out.push_str(&format!(
            "/** AOT-compiled metadata for `{}` (SQL precompiled at generation time). */\n",
            table.name
        ));
        out.push_str(&format!("export const {}_META: TableMeta = {{\n", shout(&table.name)));
        out.push_str(&format!("  table: \"{}\",\n", table.name));
        out.push_str("  columns: [\n");
        for col in &table.columns {
            let mut attrs = format!("name: \"{}\", type: \"{}\"", col.name, col.def.column_type.name());
            if col.def.nullable {
                attrs.push_str(", nullable: true");
            }
            if col.def.primary_key {
                attrs.push_str(", primaryKey: true");
            }
            out.push_str(&format!("    {{ {attrs} }},\n"));
        }
        out.push_str("  ],\n");
        out.push_str("  sql: {\n");
        out.push_str(&format!(
            "    selectAll: \"SELECT {} FROM {}\",\n",
            column_list(table),
            table.name
        ));
        out.push_str(&format!("    insert: \"{}\",\n", insert_sql(table)));
        out.push_str(&format!(
            "    countAll: \"SELECT COUNT(*) AS n FROM {}\",\n",
            table.name
        ));
        out.push_str(&format!("    deleteAll: \"DELETE FROM {}\",\n", table.name));
        out.push_str("    ident: {\n");
        for col in &table.columns {
            out.push_str(&format!("      {}: \"{}\",\n", col.name, col.name));
        }
        out.push_str("    },\n  },\n");
        if !relations.is_empty() {
            out.push_str("  relations: [\n");
            for rel in &relations {
                out.push_str(&format!(
                    "    {{ name: \"{}\", localColumn: \"{}\", foreignColumn: \"{}\", target: () => {}_META }},\n",
                    rel.name,
                    rel.local_column,
                    rel.foreign_column,
                    shout(rel.target_table)
                ));
            }
            out.push_str("  ],\n");
        }
        out.push_str("};\n\n");
    }

    out.push_str("/** The unified Powder client: one typed handle per table. */\n");
    out.push_str("export interface PowderClient {\n");
    for table in &schema.tables {
        out.push_str(&format!(
            "  {}: PowderTable<{}>;\n",
            table.name,
            pascal(&table.name)
        ));
    }
    out.push_str(
        "  /** Run `fn` inside BEGIN IMMEDIATE; commits on return, rolls back on throw. */\n",
    );
    out.push_str("  $transaction<T>(fn: (tx: PowderClient) => Promise<T>): Promise<T>;\n");
    out.push_str("}\n\n");
    out.push_str("/** Wrap a connected Ncode client with the Powder model layer. */\n");
    out.push_str("export function powder(client: Client): PowderClient {\n");
    out.push_str("  const api: PowderClient = {\n");
    for table in &schema.tables {
        out.push_str(&format!(
            "    {}: new PowderTable<{}>(client, {}_META),\n",
            table.name,
            pascal(&table.name),
            shout(&table.name)
        ));
    }
    out.push_str("    $transaction: (fn) => client.transaction(() => fn(api)),\n");
    out.push_str("  };\n  return api;\n}\n");
    out
}

/// Generate the Python model module.
pub fn python(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str("# AUTO-GENERATED by `powder generate` — do not edit.\n");
    out.push_str("# Regenerate after changing powder.schema.json.\n\n");
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("from dataclasses import dataclass\nfrom typing import Optional\n\n");
    out.push_str("from ncode import Client\n");
    out.push_str("from ncode.orm import ColumnMeta, PowderTable, RelationMeta, TableMeta\n\n");

    for table in &schema.tables {
        let ty = pascal(&table.name);
        let relations = relations_of(table);
        // kw_only: nullable/relation fields carry defaults, and Python
        // requires defaulted fields to trail positional ones otherwise.
        out.push_str("@dataclass(kw_only=True)\n");
        out.push_str(&format!("class {ty}:\n"));
        out.push_str(&format!("    \"\"\"Row shape of the `{}` table.\"\"\"\n\n", table.name));
        for col in &table.columns {
            let base = col.def.column_type.py_type();
            let py = if col.def.nullable {
                format!("Optional[{base}]{}", column_default_py(col))
            } else {
                base.to_string()
            };
            out.push_str(&format!("    {}: {}\n", col.name, py));
        }
        for rel in &relations {
            out.push_str(&format!(
                "    # Loaded via include={{\"{}\": True}}.\n    {}: Optional[{}] = None\n",
                rel.name,
                rel.name,
                pascal(rel.target_table)
            ));
        }
        out.push('\n');

        out.push_str(&format!("{}_META = TableMeta(\n", shout(&table.name)));
        out.push_str(&format!("    table=\"{}\",\n", table.name));
        out.push_str("    columns=[\n");
        for col in &table.columns {
            out.push_str(&format!(
                "        ColumnMeta(name=\"{}\", type=\"{}\", nullable={}, primary_key={}),\n",
                col.name,
                col.def.column_type.name(),
                if col.def.nullable { "True" } else { "False" },
                if col.def.primary_key { "True" } else { "False" },
            ));
        }
        out.push_str("    ],\n");
        out.push_str(&format!(
            "    select_all=\"SELECT {} FROM {}\",\n",
            column_list(table),
            table.name
        ));
        out.push_str(&format!("    insert=\"{}\",\n", insert_sql(table)));
        out.push_str(&format!(
            "    count_all=\"SELECT COUNT(*) AS n FROM {}\",\n",
            table.name
        ));
        out.push_str(&format!("    delete_all=\"DELETE FROM {}\",\n", table.name));
        out.push_str("    ident={\n");
        for col in &table.columns {
            out.push_str(&format!("        \"{}\": \"{}\",\n", col.name, col.name));
        }
        out.push_str("    },\n");
        if !relations.is_empty() {
            out.push_str("    relations=(\n");
            for rel in &relations {
                out.push_str(&format!(
                    "        RelationMeta(name=\"{}\", local_column=\"{}\", foreign_column=\"{}\", target=lambda: {}_META),\n",
                    rel.name,
                    rel.local_column,
                    rel.foreign_column,
                    shout(rel.target_table)
                ));
            }
            out.push_str("    ),\n");
        }
        out.push_str(")\n\n");
    }

    // Relation loading needs the row type of the *target* table.
    out.push_str("_ROW_TYPES = {\n");
    for table in &schema.tables {
        out.push_str(&format!(
            "    \"{}\": {},\n",
            table.name,
            pascal(&table.name)
        ));
    }
    out.push_str("}\n\n");

    out.push_str("class PowderClient:\n");
    out.push_str("    \"\"\"The unified Powder client: one typed handle per table.\"\"\"\n\n");
    out.push_str("    def __init__(self, client: Client):\n");
    out.push_str("        self._client = client\n");
    for table in &schema.tables {
        out.push_str(&format!(
            "        self.{} = PowderTable(client, {}_META, {}, row_types=_ROW_TYPES)\n",
            table.name,
            shout(&table.name),
            pascal(&table.name)
        ));
    }
    out.push('\n');
    out.push_str("    def transaction(self):\n");
    out.push_str("        \"\"\"``async with db.transaction(): ...`` — commit on exit, rollback on error.\"\"\"\n");
    out.push_str("        return self._client.transaction()\n\n");
    out.push_str("def powder(client: Client) -> PowderClient:\n");
    out.push_str("    \"\"\"Wrap a connected Ncode client with the Powder model layer.\"\"\"\n");
    out.push_str("    return PowderClient(client)\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::SAMPLE_SCHEMA;

    #[test]
    fn typescript_output_contains_aot_sql_and_types() {
        let schema = Schema::parse(SAMPLE_SCHEMA).unwrap();
        let ts = typescript(&schema, "@ncode/node");
        assert!(ts.contains("export interface Users {"));
        assert!(ts.contains("score: number | null;"));
        assert!(ts.contains("selectAll: \"SELECT id, name, score, active FROM users\""));
        assert!(ts.contains("insert: \"INSERT INTO users (id, name, score, active) VALUES (?, ?, ?, ?)\""));
        assert!(ts.contains("users: new PowderTable<Users>(client, USERS_META)"));
        // Relations: posts.user_id -> users.id surfaces as `user`.
        assert!(ts.contains("user?: Users | null;"));
        assert!(ts.contains(
            "{ name: \"user\", localColumn: \"user_id\", foreignColumn: \"id\", target: () => USERS_META }"
        ));
        assert!(ts.contains("$transaction: (fn) => client.transaction(() => fn(api))"));
    }

    #[test]
    fn python_output_contains_dataclass_and_meta() {
        let schema = Schema::parse(SAMPLE_SCHEMA).unwrap();
        let py = python(&schema);
        assert!(py.contains("@dataclass(kw_only=True)"));
        assert!(py.contains("class Users:"));
        assert!(py.contains("score: Optional[float] = None"));
        assert!(py.contains("select_all=\"SELECT id, name, score, active FROM users\""));
        assert!(py.contains("row_types=_ROW_TYPES"));
        assert!(py.contains("user: Optional[Users] = None"));
        assert!(py.contains(
            "RelationMeta(name=\"user\", local_column=\"user_id\", foreign_column=\"id\", target=lambda: USERS_META)"
        ));
        assert!(py.contains("def transaction(self):"));
    }
}
